# From here: https://support.1password.com/install-linux/#debian-or-ubuntu

- name: Download 1Password deb file
  ansible.builtin.get_url:
    url: https://downloads.1password.com/linux/debian/amd64/stable/1password-latest.deb
    dest: /tmp/

- name: Install 1Password deb file
  become: true
  ansible.builtin.apt:
    deb: 1password-latest.deb