all:
  hosts:
    pihole:
      ansible_host: 192.168.1.55
      ansible_user: olafurg
    localhost:
      ansible_connection: local
  children:
    debian:
      hosts:
        pihole:
        localhost:
