# You need to install the role first from the machine running the playbook.
# ansible-galaxy collection install prometheus.prometheus
# https://prometheus-community.github.io/ansible/branch/main/prometheus_role.html
---
- name: Install Prometheus using the prometheus.prometheus role
  include_role:
    name: prometheus.prometheus.prometheus

- name: Create Prometheus configuration file
  template:
    src: prometheus.yml.j2
    dest: "{{ prometheus_config_dir }}/prometheus.yml"
    owner: prometheus
    group: prometheus
    mode: '0755'
  become: yes

- name: Ensure Prometheus service is started and enabled
  ansible.builtin.systemd:
    name: prometheus
    state: started
    enabled: yes
  become: yes
