---
- name: Set up Ubuntu/Debian desktop
  hosts: localhost
  connection: local
  tasks:

    - name: Install basic packages
      become: true
      apt:
        name:
          - ansible
          - curl
          - git
          - glances
          - htop
          - masscan
          - nmap
          - traceroute
          - tree
          - vim
          - whois
        state: present

    - name: Install Snap packages
      become: true
      snap:
        name:
          - signal-desktop
        state: present

    - name: Install Snap packages (classic)
      become: true
      snap:
        name:
          - code # VS Code
        state: present
        classic: true

  roles:
    # - 1password-debian-ubuntu-desktop
    - asdf
    - gh
    - git
    - oh_my_zsh
    - terraform
    - tmux
    - vim
