---
- name: Set up Ubuntu desktop localhost
  hosts: localhost
  connection: local
  tasks:

    - name: Install basic packages
      become: true
      apt:
        name:
          - ansible
          - curl
          - git
          - glances
          - htop
          - masscan
          - nmap
          - traceroute
          - tree
          - ttf-mscorefonts-installer
          - vim
          - whois
        state: latest
        update_cache: true
    
    - name: Install snap packages
      become: true
      snap:
        name:
          - code
          - signal
        state: present

  roles:
    - 1password-debian-ubuntu-desktop
    - asdf
    - base-packages-debian
    - gh
    - git
    - oh_my_zsh
    - terraform
    - tmux
    - vim    
