---
- name: Add key for Terraform
  become: true
  ansible.builtin.apt_key:
    url: https://apt.releases.hashicorp.com/gpg
    state: present

- name: Get lsb_release
  command: "lsb_release -cs"
  changed_when: false
  register: lsb_rel

- name: Add Terraform repository into sources list
  become: true
  ansible.builtin.apt_repository:
    repo: "deb https://apt.releases.hashicorp.com {{ lsb_rel.stdout }} main"
    state: present

- name: Install Terraform
  become: true
  apt:
    name: terraform
    state: present
    update_cache: yes