---
- name: Install vim
  become: true
  apt:
    name:
      - vim
    state: present

- name: Put .vimrc in place
  copy:
    src=../files/.vimrc
    dest=~/

- name: Put .vim directory in place
  copy:
    src=../folders/.vim
    dest=~/