---
- name: Install Zsh and Git
  become: true
  apt:
    name:
      - zsh
      - git
    state: present

- name: Check if .zshrc exists
  stat:
    path: ~/.zshrc
  register: stat_rc_result

- name: Check if .oh-my-zsh exists
  stat:
    path: ~/.oh-my-zsh
  register: stat_oh_my_zsh

- name: Get oh-my-zsh install script if needed
  get_url: 
    url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
    dest: /tmp
  when: not stat_oh_my_zsh.stat.exists

- name: Install oh-my-zsh if needed
  command: sh /tmp/install.sh
  register: stat_install_oh_my_zsh
  when: not stat_oh_my_zsh.stat.exists

- name: Replace default .zshrc with custom one
  copy:
    src=../files/.zshrc
    dest=~/.zshrc

- name: Put custom aliases file in place
  copy:
    src=../files/aliases.zsh
    dest=~/.oh-my-zsh/custom/

- name: Change default shell to (oh-my-)zsh
  vars:
    current_user: "{{ ansible_user_id }}"
  become: true
  user:
    name: "{{ current_user }}"
    shell: /usr/bin/zsh

- name: Ask user to reboot
  ansible.builtin.debug:
    msg:
    - "PLEASE REBOOT YOUR COMPUTER FOR CHANGES TO TAKE EFFECT"
