---
- name: Install and configure git
  become: true
  apt:
    name:
      - git
    state: present

- name: Put gitconfig file in place
  copy:
    src=../files/.gitconfig
    dest=~/

- name: Put gitignore file in place
  copy:
    src=../files/.gitignore
    dest=~/
