- name: Install basic packages
  become: true
  apt:
    name:
      - curl
      - git
      - htop
      - masscan
      - sshpass
      - nmap
      - tree
      - traceroute
      - vim
      - whois
    state: present
    update_cache: true