---
- name: Set up Ubuntu WSL localhost
  hosts: localhost
  connection: local
  tasks:
    - name: Install basic packages
      become: true
      apt:
        name:
          - vim
          - git
          - curl
          - htop
          - tree
          - traceroute
          - nmap
          - masscan
          - glances
          - whois
        state: present
        update_cache: true

  roles:
    - oh_my_zsh
    - git
    - vim
    - tmux
    - terraform
    - azure_cli
    - gh
    - 1password-wsl
    - asdf
    - prometheus
    - grafana
    - node_exporter