# WSL piece is taken from here mostly: https://dev.to/d4vsanchez/use-1password-ssh-agent-in-wsl-2j6m
---
- name: Install WSL prerequisites for 1Password setup
  become: true
  apt:
    name: socat
    state: present

- name: Make $HOME/.1password directory
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.1password"
    state: directory

- name: Move .agent-bridge to its place and make executable
  ansible.builtin.copy:
    src: ../files/.agent-bridge.sh
    dest: "{{ ansible_env.HOME }}/.agent-bridge.sh"

- name: Ensure .agent-bridge.sh is executable
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.agent-bridge.sh"
    mode: '0755'

- name: Add source command to .zshrc
  ansible.builtin.lineinfile:
    path: "{{ ansible_env.HOME }}/.zshrc"
    line: 'source $HOME/.agent-bridge.sh'
    create: yes
