---
- name: Install and configure GitHub CLI
  become: true
  apt:
    name:
      - curl
    state: present

# TODO: make this more Ansible like
- name: Fetch and add official GitHub CLI sources
  # From here: https://github.com/cli/cli/blob/trunk/docs/install_linux.md
  become: true
  shell:
    cmd: |
      curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg \
      && sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg \
      && echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null \

- name: Update sources and install GitHub CLI
  become: true
  apt:
    name: 
      - gh
    state: present
    update_cache: true