---
- name: Ensure base packages are installed
  become: true
  apt:
    name:
      - ca-certificates
      - curl
      - apt-transport-https
      - lsb-release
      - gnupg
    state: present

- name: Add MS signing key
  become: true
  ansible.builtin.apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
    state: present

- name: Get lsb_release
  command: "lsb_release -cs"
  changed_when: false
  register: lsb_rel

- name: Add azure-cli repository into sources list
  become: true
  ansible.builtin.apt_repository:
    repo: "deb https://packages.microsoft.com/repos/azure-cli/ {{ lsb_rel.stdout }} main"
    state: present
    filename: azure_cli

- name: Install azure-cli
  become: true
  apt:
    name: azure-cli
    state: present
    update_cache: yes